name: Convco
description: Performs convco checks, generates changelogs, and determines versions.
branding:
  icon: git-commit
  color: orange
inputs:
  command:
    description: The convco command to run (check, changelog, version)
    required: true
  options:
    description: Additional options for the convco command
    default: ''
  convco_version:
    description: 'The convco version to download (default: latest)'
    default: latest
outputs:
  result:
    description: The output of the convco command
runs:
  using: 'node16'
  main: 'index.js'