name: Convco check
on: [ pull_request ]
jobs:
    check:
        name: convco check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Convco
              uses: ./ # convco/convco-action@v0.1.0
            - name: Convco check
              run: convco check
